name = "GamersReloaded"
author = "Gamers"
version = "1.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19b6a99f497e3450573479ec024c89739ec05ba9ccd4c5d11a44d2d39c982d5b"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
