name = "GamersReloaded"
author = "Gamers"
version = "1.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28a0009b6acf55dae1b00f29e6f00f73763b327a842181fd8cdb96cdd8504493"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
