name = "GamersReloaded"
author = "Gamers"
version = "1.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "080fdbbd1e2f89c12eb325c62e1a466112b7b14de26a59fdc68c96df5dfbf74c"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
