name = "GamersReloaded"
author = "Gamers"
version = "1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94c282a50f2ebf11a0f60ebbffccd54a1baedf0e358ef289b3dbaad014d99070"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
