name = "GamersReloaded"
author = "Gamers"
version = "1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45b515305605c29ec81bc15459b12334c9c0ebc5e02e204182d0a7e3ef2d9add"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
